version: '3'
services:
    db:
        container_name: mysql-container
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: health-service
            MYSQL_ROOT_PASSWORD: asdf1235
        networks:
            - "microservicenetwork"
    discovery:
        container_name: discovery-service-container
        build:
            context: discovery-service
            dockerfile: Dockerfile
        image: health-project/discovery-service
        ports:
            - "8761:8761"
        networks:
            - "microservicenetwork"
    gateway:
        container_name: gateway-service-container
        depends_on:
            - discovery
        build:
            context: gateway-service
            dockerfile: Dockerfile
        image: health-project/gateway-service
        ports:
            - "8080:8080"
        networks:
            - "microservicenetwork"
    health:
        container_name: health-service-container
        depends_on:
            - discovery
            - gateway
        build:
            context: health-service
            dockerfile: Dockerfile
        image: health-project/health-service
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://zutbasement.synology.me:3306/health-service?autoReconnect=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: asdf1235
        networks:
            - "microservicenetwork"
  
networks:
    microservicenetwork:
        driver: bridge