version: '2'
services:
    eureka:
        container_name: eureka-service-container
        build:
            context: eureka-service
            dockerfile: Dockerfile
        image: eureka-service-image
        ports:
            - "8761:8761"
        networks:
            - "microservicenetwork"
    user:
        container_name: user-service-container
        build:
            context: user-service
            dockerfile: Dockerfile
        image: user-service-container
        ports:
            - "8081:8081"
        networks:
            - "microservicenetwork"
networks:
    microservicenetwork:
        driver: bridge