spring:
  application:
    name: user-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-service-container:8761/eureka}
  instance:
    preferIpAddress: true